#version: "3.5"

# If you already have redis in another docker stack you can specify here that network.
# And then also specify the network in the 'hdx-sdd' service
networks:
  redis-network:
    name: hdx_geo_local_default
    external: true
  db:
    external: true

services:
  hdx-sdd:
    image: public.ecr.aws/unocha/hdx-sdd:dev
#    build: .
    hostname: hdx-sdd
    volumes:
      - ".:/srv/sdd"
      - ".ssh/authorized_keys:/root/.ssh/authorized_keys"
    ports:
      - "60066:22"
    environment:
      # LISTENER_MODE: ${LISTENER_MODE:-true}
      WORKER_ENABLED: ${WORKER_ENABLED:-true}
      REDIS_STREAM_HOST: ${REDIS_STREAM_HOST:-redis}
      REDIS_STREAM_PORT: ${REDIS_STREAM_PORT:-6379}
      REDIS_STREAM_DB: ${REDIS_STREAM_DB:-7}
      REDIS_STREAM_STREAM_NAME: ${REDIS_STREAM_STREAM_NAME:-hdx_event_stream}
      REDIS_STREAM_GROUP_NAME: ${REDIS_STREAM_GROUP_NAME:-hdx_sdd_group}
      REDIS_STREAM_CONSUMER_NAME: ${REDIS_STREAM_CONSUMER_NAME:-hdx_sdd_consumer_1}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT:-https://your-resource.openai.azure.com/}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY:-your-api-key-here}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION:-2024-02-15-preview}
      HDX_URL: ${HDX_URL:-https://data.humdata.local}
      HDX_KEY: ${HDX_KEY:-YOUR_HDX_TOKEN}
      HDX_SDD_SLACK_ACCESS_TOKEN: ${HDX_SDD_SLACK_ACCESS_TOKEN:-your-token-here}
      OPENAI_ENDPOINT: ${OPENAI_ENDPOINT:-https://your-resource.openai.azure.com/}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your-api-key-here}
      ISP_STRATEGY: ${ISP_STRATEGY:-google_sheets}
      ISP_GOOGLE_SHEET_URL: ${ISP_GOOGLE_SHEET_URL:-https://docs.google.com/spreadsheets/d/your-spreadsheet-id/edit}
      GOOGLE_SHEETS_PRIVATE_KEY: ${GOOGLE_SHEETS_PRIVATE_KEY:-your-private-key-here}
      GOOGLE_SHEETS_CLIENT_EMAIL: ${GOOGLE_SHEETS_CLIENT_EMAIL:-your-service-account-email@example.com}
      GOOGLE_SHEETS_TOKEN_URI: ${GOOGLE_SHEETS_TOKEN_URI:-https://oauth2.googleapis.com/token}
    entrypoint: [ "tail", "-f", "/dev/null" ]
    networks:
      - redis-network
      - db
